apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: devops
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: uros02/mitra88-devops-backend:1.21
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/myappdb"
