pipeline {
    agent any
    
    tools {
        nodejs "NODEJS"
    }

    environment {
        CHROME_BIN = '/usr/bin/google-chrome-stable'
    }
    
    stages {
        
        stage('Fetching code') {
            steps {
                git branch: 'main', url: 'https://github.com/Mitra8888/devops.git'
            }
        }
        
        stage('Unit testing') {
            steps {
                dir('frontend') {
                    sh 'npm ci'
                    sh 'npm test -- --watch=false --no-progress'
                }
            }
        }
        
        stage('Build') {
            steps {
                dir('frontend') {
                    sh 'npm run build'
                }
            }
            post {
                success {
                    echo "Archiving artifact"
                    archiveArtifacts artifacts: 'frontend/build/**'
                }
            }
        }
    }
}