pipeline {
    agent any
    
    tools {
        nodejs "NODEJS"
        sonarqube "sonar8.0"
    }

    environment {
        CHROME_BIN = '/usr/bin/google-chrome-stable'
        PROJECT_NAME = 'devops'
        FRONTEND_REPO = 'uros02/mitra88-devops-frontend-jk'
        BACKEND_REPO = 'uros02/mitra88-devops-backend-jk'
        VERSION = "2.${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Fetching code') {
            steps {
                git branch: 'main', url: 'https://github.com/Mitra8888/devops.git'
            }
        }
        
        stage('Unit testing') {
            steps {
                dir('frontend') {
                    sh 'npm ci'
                    sh 'npm test -- --watch=false --no-progress --code-coverage'
                }
            }
        }
        
        stage ('SonarQube Scan') {
            steps {
                dir('frontend'){
                    withSonarQubeEnv('SonarQube'){
                        withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]){
                            sh 'npx sonarqube-scanner -Dsonar.token=$SONAR_TOKEN'
                        }
                    }
                }
            }
        }
        stage ('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }


        stage('Build') {
            steps {
                dir('frontend') {
                    sh 'npm run build'
                }
            }
            post {
                success {
                    echo "Archiving artifact"
                    archiveArtifacts artifacts: 'frontend/dist/**'
                }
            }
        }

         stage ('Upload to Nexus') {
            steps {
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: 'http://nexus:8081',
                    groupId: 'QA',
                    version: "${VERSION}",
                    repository: 'devops-frontend-repo',
                    credentialsId: 'nexuslogin',
                    artifacts: [
                        [artifactId: 'devops-frontend',
                        classifier: '',
                        file: "frontend/devops-frontend-${BUILD_NUMBER}.zip",
                        type: 'zip']
                        ]
                     )
                }
            }

    //     stage ('Build Docker images') {
    //         steps {
    //             sh 'docker compose -p $PROJECT_NAME build'
    //         }
    //     }

    //     stage ('Push Docker images') {
    //         steps {
    //             withCredentials([usernamePassword(
    //                 credentialsId: 'docker-hub-credentials',
    //                 usernameVariable: 'DOCKER_USERNAME',
    //                 passwordVariable: 'DOCKER_PASSWORD'
    //             )]){
    //                 sh 'echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin'

    //                 script {
    //                     // Frontend
    //                     def frontendImageId = sh(script: "docker images -q ${PROJECT_NAME}-frontend", returnStdout: true).trim()
    //                     sh "docker tag ${frontendImageId} ${FRONTEND_REPO}:latest"
    //                     sh "docker push ${FRONTEND_REPO}:latest"
    //                     sh "docker tag ${frontendImageId} ${FRONTEND_REPO}:${VERSION}"
    //                     sh "docker push ${FRONTEND_REPO}:${VERSION}"


    //                     // Backend
    //                     def backendImageId = sh(script: "docker images -q ${PROJECT_NAME}-backend", returnStdout: true).trim()
    //                     sh "docker tag ${backendImageId} ${BACKEND_REPO}:latest"
    //                     sh "docker push ${BACKEND_REPO}:latest"
    //                     sh "docker tag ${backendImageId} ${BACKEND_REPO}:${VERSION}"
    //                     sh "docker push ${BACKEND_REPO}:${VERSION}"
    //                 }
    //             }
    //         }
    //     }
    // }
    // post {
    //     always {
    //         sh 'docker logout'
    //     }
    // }
    }
}