name: CI with Cypress and Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install frontend deps
        run: |
          cd frontend
          npm ci &
      - name: Install backend deps
        run: |
          cd backend
          npm ci &
      
      - name: Wait for servers
        run: 
          echo "giving servers 10 seconds to initialize"
          sleep 10
          echo "Starting wait-on for localhost:4200 and localhost:3000..."
          npx wait-on http-get://localhost:4200 http-get://localhost:3000 --timeout 60000

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          spec: frontend/cypress/e2e/login-test/login-test.cy.ts