- name: run node exporter
  community.docker.docker_container:
    name: node_exporter
    image: prom/node-exporter
    state: started
    restart_policy: unless-stopped
    ports:
      - "9100:9100"